-- MySQL Script generated by MySQL Workbench
-- Tue Oct  3 15:25:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `idEvent` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEvent`),
  UNIQUE INDEX `idEvent_UNIQUE` (`idEvent` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scheme_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scheme_User` (
  `idEvent` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idEvent`, `idUser`),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `scheme_User_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `mydb`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Group` (
  `idGroup` INT NOT NULL,
  `idEvent` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGroup`),
  UNIQUE INDEX `idGroup_UNIQUE` (`idGroup` ASC),
  INDEX `idEvent_idx` (`idEvent` ASC),
  CONSTRAINT `Group_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `mydb`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aisle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aisle` (
  `idAisle` INT NOT NULL,
  `idEvent` INT NOT NULL,
  `Row` INT NOT NULL,
  `Left_Seat` INT NOT NULL,
  PRIMARY KEY (`idAisle`),
  INDEX `idEvent_idx` (`idEvent` ASC),
  UNIQUE INDEX `idAisle_UNIQUE` (`idAisle` ASC),
  CONSTRAINT `Aisle_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `mydb`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `idReservation` INT NOT NULL,
  `idEvent` INT NOT NULL,
  `idGroup` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Comment` VARCHAR(45) NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`idReservation`),
  UNIQUE INDEX `idReservation_UNIQUE` (`idReservation` ASC),
  INDEX `idEvent_idx` (`idEvent` ASC),
  INDEX `idGroup_idx` (`idGroup` ASC),
  CONSTRAINT `Reservation_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `mydb`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Reservation_idGroup`
    FOREIGN KEY (`idGroup`)
    REFERENCES `mydb`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seat` (
  `Row` VARCHAR(45) NOT NULL,
  `Seat` VARCHAR(45) NOT NULL,
  `idReservation` INT NOT NULL,
  `idEvent` INT NOT NULL,
  PRIMARY KEY (`Row`, `Seat`),
  INDEX `idReservation_idx` (`idReservation` ASC),
  INDEX `idEvent_idx` (`idEvent` ASC),
  CONSTRAINT `Seat_idReservation`
    FOREIGN KEY (`idReservation`)
    REFERENCES `mydb`.`Reservation` (`idReservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Seat_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `mydb`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
