-- MySQL Script generated by MySQL Workbench
-- Tue Oct  3 15:25:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tickets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tickets` DEFAULT CHARACTER SET utf8 ;
USE `tickets` ;

-- -----------------------------------------------------
-- Table `tickets`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tickets`.`Event` (
  `idEvent` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEvent`),
  UNIQUE INDEX `idEvent_UNIQUE` (`idEvent` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tickets`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tickets`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(64) NOT NULL,
  `Username` VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tickets`.`Scheme_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tickets`.`Event_User` (
  `idEvent` INT,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idEvent`, `idUser`),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `scheme_User_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `tickets`.`Event` (`idEvent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `tickets`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tickets`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tickets`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `idEvent` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`),
  UNIQUE INDEX `idCategory_UNIQUE` (`idCategory` ASC),
  INDEX `idEvent_idx` (`idEvent` ASC),
  CONSTRAINT `Category_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `tickets`.`Event` (`idEvent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tickets`.`Aisle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tickets`.`Aisle` (
  `idAisle` INT NOT NULL AUTO_INCREMENT,
  `idEvent` INT NOT NULL,
  `Row` INT NOT NULL,
  `Left_Seat` INT NOT NULL,
  `Width` INT NOT NULL,
  PRIMARY KEY (`idAisle`),
  INDEX `idEvent_idx` (`idEvent` ASC),
  UNIQUE INDEX `idAisle_UNIQUE` (`idAisle` ASC),
  CONSTRAINT `Aisle_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `tickets`.`Event` (`idEvent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tickets`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tickets`.`Reservation` (
  `idReservation` INT NOT NULL AUTO_INCREMENT,
  `idEvent` INT NOT NULL,
  `idCategory` INT,
  `Name` VARCHAR(45) NOT NULL,
  `Comment` VARCHAR(45),
  `Color` VARCHAR(8),
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`idReservation`),
  UNIQUE INDEX `idReservation_UNIQUE` (`idReservation` ASC),
  INDEX `idEvent_idx` (`idEvent` ASC),
  INDEX `idCategory_idx` (`idCategory` ASC),
  CONSTRAINT `Reservation_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `tickets`.`Event` (`idEvent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Reservation_idCategory`
    FOREIGN KEY (`idCategory`)
    REFERENCES `tickets`.`Category` (`idCategory`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tickets`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tickets`.`Seat` (
  `Row` INT NOT NULL,
  `Seat` INT NOT NULL,
  `idReservation` INT,
  `idEvent` INT NOT NULL,
  PRIMARY KEY (`Row`, `Seat`, `idEvent`),
  INDEX `idReservation_idx` (`idReservation` ASC),
  INDEX `idEvent_idx` (`idEvent` ASC),
  CONSTRAINT `Seat_idReservation`
    FOREIGN KEY (`idReservation`)
    REFERENCES `tickets`.`Reservation` (`idReservation`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `Seat_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `tickets`.`Event` (`idEvent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
